# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190613_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='操作权限')),
                ('url', models.CharField(max_length=48, verbose_name='url路径')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色')),
                ('permission', models.ManyToManyField(blank=True, null=True, to='app01.Permission', verbose_name='权限')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='null', help_text='学员报名后，请改为真实姓名', max_length=32, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='app01.Role', verbose_name='角色'),
        ),
    ]
