# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190617_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='ico',
            field=models.CharField(default='fa fa-link', max_length=32, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.BooleanField(default=False, verbose_name='是否为菜单'),
        ),
    ]
